#!/usr/bin/env groovy
pipeline {
    agent any
    environment {
        // Jenkins will use the credentials added earlier
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = "us-east-1"
    }
    stages {
        stage("Deploy to EKS") {
            steps {
                script {
                    dir('k8s-yaml') {
                        // Update packages inside the cluster
                        sh "aws eks update-kubeconfig --name niks-cluster"
                        // Deploy all yamls
                        sh "kubectl apply -f ."
                    }
                }
            }
        }
    }
}